[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 5 # Or your preferred number of runs
via_ir = true # Add or set this to true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
